# Generated by Django 5.2.6 on 2026-03-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_testimonial_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.blogpost',),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
